In [59]:
import numpy as np
import galois

In [60]:
def f(x):
    return 1 + x + x**2


def g(x):
    return 2 + 12 * x**3


def dft(poly, w, ring, order):
    # return list of coefficients of increasing order for dft of poly
    return [poly(w**i) % ring for i in range(order)]

In [65]:
args = {
    "poly": f,
    "w": 4,
    "order": 6,
    "ring": 13,
}

dft_f = np.array(dft(**args))

args["poly"] = g

dft_g = np.array(dft(**args))

print(dft_f)
print(dft_g)

dft_fg = (dft_f * dft_g) % args["ring"]

print(dft_fg)

[3 8 0 1 0 7]
[1 3 1 3 1 3]
[ 3 11  0  3  0  8]


7x^5 + x^3 + 8x + 3
3x^5 + x^4 + 3x^3 + x^2 + 3x + 1


Poly(8x^10 + 7x^9 + 11x^8 + 8x^7 + 9x^6 + 12x^5 + 4x^4 + 5x^3 + x^2 + 4x + 3, GF(13))