In [1]:
import numpy as np
import galois

In [2]:
def f(x):
    return 1 + x + x**2


def g(x):
    return 2 + 12 * x**3


def dft_fg1(x):
    return 3 + 11 * x + 3 * x**3 + 8 * x**5


def dft(poly, w, ring, order):
    # return list of coefficients of increasing order for dft of poly
    return [poly(w**i) % ring for i in range(order)]

In [3]:
args = {
    "poly": f,
    "w": 4,
    "order": 6,
    "ring": 13,
}

dft_f = np.array(dft(**args))

args["poly"] = g

dft_g = np.array(dft(**args))

print(dft_f)
print(dft_g)

dft_fg = (dft_f * dft_g) % args["ring"]

print(dft_fg)

[3 8 0 1 0 7]
[1 3 1 3 1 3]
[ 3 11  0  3  0  8]


In [4]:
args["poly"] = dft_fg1
args["w"] = 10

dft_inv = np.array(dft(**args))

# order of coeffs wrong because of modulating twice: once in function and then here
# remove modulo in function to obtain correct results
11 * dft_inv % 13

array([ 2,  2,  2, 12, 12, 12], dtype=int32)

In [5]:
F = galois.GF(13)

f_p = galois.Poly([1, 1, 1], F)
g_p = galois.Poly([12, 0, 0, 2], F)

f_p * g_p

Poly(12x^5 + 12x^4 + 12x^3 + 2x^2 + 2x + 2, GF(13))