In [6]:
import numpy as np
import galois

In [12]:
GF = galois.GF(113)

V = GF(
    [
        [1, 1, 1, 1, 1],
        [1, 2, 4, 8, 16],
        [1, 3, 9, 27, 81],
        [1, 4, 16, 64, 30],
        [1, 5, 25, 12, 60],
    ]
)

x = GF([63, 35, 3, 9, 36])

V_ = np.linalg.inv(V)

print(V_)


np.matmul(V_, x)

[[  5 103  10 108   1]
 [  3 112  37  29  45]
 [ 83   9  97  12  25]
 [103  21 110  96   9]
 [ 33  94  85  94  33]]


GF([ 99, 112,  63,  41,  87], order=113)