In [38]:
import numpy as np

In [39]:
def coords(i, j, k, n):
    return (i * n + k, i * n + j, j * n + k)

In [40]:
n = 2
for i in range(n):
    for j in range(n):
        for k in range(n):
            print(coords(i, j, k, n))

(0, 0, 0)
(1, 0, 1)
(0, 1, 2)
(1, 1, 3)
(2, 2, 0)
(3, 2, 1)
(2, 3, 2)
(3, 3, 3)


In [41]:
def kruskal(A, B, C, n, r):
    T = np.zeros((n, n, n))
    for i in range(n):
        for j in range(n):
            for k in range(n):
                for l in range(r):
                    T[i][j][k] += A[i][l]  \
                        * B[j][l] * C[k][l]
    return T.astype(int)

In [42]:
A = np.array(
    [
        [0, 1, 0, 0, 0, 0, 1],
        [-1, -1, 0, 1, 1, 0, 0],
        [0, -1, 1, 1, 0, 1, 0],
        [1, 1, -1, -1, 0, 0, 0],
    ]
)

B = np.array(
    [
        [0, 0, 0, 0, 1, 0, 1],
        [0, 1, 1, 1, 1, 0, 0],
        [1, 0, 0, 1, 1, 1, 0],
        [1, 0, 1, 1, 1, 0, 0],
    ]
)

C = np.array(
    [
        [0, 0, 0, 0, 0, 1, 1],
        [0, 0, 1, -1, 1, 1, 0],
        [1, 1, 0, 1, 0, -1, 0],
        [1, 0, -1, 1, 0, -1, 0],
    ]
)

In [43]:
U = np.array([[1, 2], [3, 4]])
V = np.array([[5, 6], [7, 8]])

np.matmul(U, V)

array([[19, 22],
       [43, 50]])

In [44]:
def tensor_map(T, u, v):
    w = np.zeros(len(T))

    for i in range(len(T)):
        for j in range(len(u)):
            for k in range(len(v)):
                w[i] += T[i][j][k] * u[j] * v[k]
    return w.astype(int)

In [45]:
M_2 = kruskal(A, B, C, 4, 7)
u = np.array([1, 2, 3, 4])
v = np.array([5, 6, 7, 8])

tensor_map(M_2, u, v)

array([19, 22, 43, 50])

In [52]:
Bu = np.matmul(np.transpose(B), u)
Cv = np.matmul(np.transpose(C), v)

print(Bu, Cv)

print(Bu * Cv)

np.matmul(A, Bu * Cv)

[ 7  2  6  9 10  3  1] [15  7 -2  9  6 -4  5]
[105  14 -12  81  60 -12   5]


array([19, 22, 43, 50])